CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url VARCHAR(250) NOT NULL,
    description TEXT,
    rating INTEGER CHECK (rating >= 0 AND rating <= 5) NOT NULL
);